version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "s3code"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - sudo apt-get install zip unzip
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            -  zip -r dist.zip dist
            - aws s3 cp dist.zip s3://s3code --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
