version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "s3code"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - cp appspec.yml install_dependencies  start_server stop_server file_replace dist
            - aws s3 cp -rf dist s3://s3code --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
